backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: settings
    label: Site Settings
    format: json
    editor: { preview: false }
    files:
      - name: settings
        label: Settings
        file: data/settings.json
        fields:
          - { label: "Site Title", name: siteTitle, widget: string }
          - { label: "Logo", name: logo, widget: image, required: false }
          - label: Colors
            name: colors
            widget: object
            fields:
              - { label: Primary, name: primary, widget: color, default: "#0a0a0a" }
              - { label: Secondary, name: secondary, widget: color, default: "#111827" }
              - { label: Accent, name: accent, widget: color, default: "#6b7280" }
              - { label: Background, name: bg, widget: color, default: "#fafafa" }
              - { label: Text, name: text, widget: color, default: "#0a0a0a" }
          - { label: "Hero Title", name: heroTitle, widget: string }
          - { label: "Hero Text", name: heroText, widget: text }
          - label: Trust Stats
            name: trustStats
            widget: list
            field: { label: Item, name: item, widget: string }
          - { label: "Footer Note", name: footerNote, widget: string, required: false }

  - name: steps
    label: Registration Steps
    format: json
    editor: { preview: false }
    files:
      - name: steps
        label: Steps
        file: data/steps.json
        fields:
          - label: Steps
            name: items
            widget: list
            fields:
              - { label: Label, name: label, widget: string }

  - name: events
    label: Events
    format: json
    editor: { preview: false }
    files:
      - name: events
        label: Events List
        file: data/events.json
        fields:
          - label: Events
            name: items
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD" }
              - { label: Time, name: time, widget: string, required: false }
              - { label: Type, name: type, widget: string, required: false }
              - { label: Location, name: location, widget: string, required: false }
              - { label: Price, name: price, widget: string, required: false }
              - { label: Cover Image, name: coverImage, widget: image, required: false }

  - name: programs
    label: Programs
    format: json
    editor: { preview: false }
    files:
      - name: programs
        label: Programs List
        file: data/programs.json
        fields:
          - label: Programs
            name: items
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Cadence, name: cadence, widget: string, required: false }

  - name: partners
    label: Tech Partners
    format: json
    editor: { preview: false }
    files:
      - name: partners
        label: Partners Grid
        file: data/partners.json
        fields:
          - label: Partners
            name: items
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: image, required: false }
              - { label: URL, name: url, widget: string, required: false }
              - { label: Blurb, name: blurb, widget: string, required: false }
              - { label: Featured, name: featured, widget: boolean, default: true }

  - name: studios
    label: Studios
    format: json
    editor: { preview: false }
    files:
      - name: studios
        label: Studios List
        file: data/studios.json
        fields:
          - label: Studios
            name: items
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Booking Link, name: bookingLink, widget: string, required: false }
